<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adaptertype"
    nsURI="http://kieler.cs.cau.de/cakefeed/adaptertype" nsPrefix="adaptertype">
  <eClassifiers xsi:type="ecore:EClass" name="AdapterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Identification" eType="ecore:EClass system.ecore#//Identification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VersionInfo" lowerBound="1"
        upperBound="-1" eType="ecore:EClass system.ecore#//VersionInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CompilerInfo" eType="ecore:EClass system.ecore#//CompilerInfo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InterfaceList" lowerBound="1"
        eType="ecore:EClass system.ecore#//InterfaceList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Service" eType="#//Service"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceSequence" lowerBound="1"
        upperBound="-1" eType="#//ServiceSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RightInterface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LeftInterface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceTransaction" upperBound="-1"
        eType="#//ServiceTransaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTransaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="InputPrimitive" eType="#//InputPrimitive"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutputPrimitive" upperBound="-1"
        eType="#//OutputPrimitive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPrimitive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Event" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Interface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPrimitive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Event" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Interface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
