<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cakefeed"
    nsURI="http://kieler.cs.cau.de/cakefeed" nsPrefix="cakefeed">
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlocksInstances"
        upperBound="-1" eType="#//FunctionBlockInstance" containment="true" eOpposite="#//FunctionBlockInstance/parentApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true" eOpposite="#//Connection/parentApplication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlock" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentInterface" lowerBound="1"
        eType="#//Interface" eOpposite="#//Interface/functionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEventPorts" upperBound="-1"
        eType="#//InputEventPort" containment="true" eOpposite="#//InputEventPort/parentFunctionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEventPorts" upperBound="-1"
        eType="#//OutputEventPort" containment="true" eOpposite="#//OutputEventPort/parentFunctionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputDataPorts" upperBound="-1"
        eType="#//InputDataPort" containment="true" eOpposite="#//InputDataPort/parentFunctionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDataPorts" upperBound="-1"
        eType="#//OutputDataPort" containment="true" eOpposite="#//OutputDataPort/parentFunctionBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFunctionBlock" eSuperTypes="#//FunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionControlChart"
        eType="ecore:EClass ../../de.cau.cs.kieler.synccharts/model/synccharts.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithms" upperBound="-1"
        eType="#//Algorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeFunctionBlock" eSuperTypes="#//FunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeNetwork" lowerBound="1"
        eType="#//CompositeNetwork" containment="true" eOpposite="#//CompositeNetwork/parentCompositeFunctionBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSequence" eType="#//ServiceSequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterfaceFunctionBlock" eSuperTypes="#//FunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSequence" eType="#//ServiceSequence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionBlockInstance" abstract="true"
      eSuperTypes="#//FunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentApplication" lowerBound="1"
        eType="#//Application" eOpposite="#//Application/functionBlocksInstances"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFunctionBlockInstance" eSuperTypes="#//FunctionBlockInstance #//BasicFunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//BasicFunctionBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeFunctionBlockInstance" eSuperTypes="#//FunctionBlockInstance #//CompositeFunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//CompositeFunctionBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterfaceFunctionBlockInstance"
      eSuperTypes="#//FunctionBlockInstance #//ServiceInterfaceFunctionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ServiceInterfaceFunctionBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentApplication" lowerBound="1"
        eType="#//Application" eOpposite="#//Application/connections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEventPort" lowerBound="1"
        eType="#//OutputEventPort" eOpposite="#//OutputEventPort/eventConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEventPort" lowerBound="1"
        eType="#//InputEventPort" eOpposite="#//InputEventPort/eventConnections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDataPort" lowerBound="1"
        eType="#//OutputDataPort" eOpposite="#//OutputDataPort/eventConnections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDataPort" lowerBound="1"
        eType="#//InputDataPort" eOpposite="#//InputDataPort/eventConnections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPort" abstract="true" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataPort" abstract="true" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" lowerBound="1"
        eType="#//PortType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputEventPort" eSuperTypes="#//EventPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFunctionBlock" lowerBound="1"
        eType="#//FunctionBlock" eOpposite="#//FunctionBlock/inputEventPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventConnections" upperBound="-1"
        eType="#//EventConnection" eOpposite="#//EventConnection/targetEventPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputAssociations" upperBound="-1"
        eType="#//InputAssociation" containment="true" eOpposite="#//InputAssociation/sourceInputEventPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputEventPort" eSuperTypes="#//EventPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFunctionBlock" lowerBound="1"
        eType="#//FunctionBlock" eOpposite="#//FunctionBlock/outputEventPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventConnections" upperBound="-1"
        eType="#//EventConnection" eOpposite="#//EventConnection/sourceEventPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputAssociations" upperBound="-1"
        eType="#//OutputAssociation" containment="true" eOpposite="#//OutputAssociation/sourceOutputEventPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputDataPort" eSuperTypes="#//DataPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFunctionBlock" lowerBound="1"
        eType="#//FunctionBlock" eOpposite="#//FunctionBlock/inputDataPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventConnections" upperBound="-1"
        eType="#//DataConnection" eOpposite="#//DataConnection/targetDataPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputAssociations" upperBound="-1"
        eType="#//InputAssociation" eOpposite="#//InputAssociation/targetInputDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDataPort" eSuperTypes="#//DataPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFunctionBlock" lowerBound="1"
        eType="#//FunctionBlock" eOpposite="#//FunctionBlock/outputDataPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventConnections" upperBound="-1"
        eType="#//DataConnection" eOpposite="#//DataConnection/sourceDataPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputAssociations" upperBound="-1"
        eType="#//OutputAssociation" eOpposite="#//OutputAssociation/targetOutputDataPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithmName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithmLanguage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithmSourceCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeNetwork" eSuperTypes="#//Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentCompositeFunctionBlock"
        lowerBound="1" eType="#//CompositeFunctionBlock" eOpposite="#//CompositeFunctionBlock/compositeNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" eType="#//OutputEventPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEvents" eType="#//InputEventPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" eType="#//OutputDataPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputData" eType="#//InputDataPort"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceInputEventPort" lowerBound="1"
        eType="#//InputEventPort" eOpposite="#//InputEventPort/inputAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetInputDataPort" lowerBound="1"
        eType="#//InputDataPort" eOpposite="#//InputDataPort/inputAssociations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputAssociation" eSuperTypes="#//Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceOutputEventPort"
        lowerBound="1" eType="#//OutputEventPort" eOpposite="#//OutputEventPort/outputAssociations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOutputDataPort" lowerBound="1"
        eType="#//OutputDataPort" eOpposite="#//OutputDataPort/outputAssociations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortType">
    <eLiterals name="BYTE"/>
    <eLiterals name="DT" value="1"/>
    <eLiterals name="LREAL" value="2"/>
    <eLiterals name="UINT" value="3"/>
    <eLiterals name="LINT" value="4"/>
    <eLiterals name="BOOL" value="5"/>
    <eLiterals name="DATE_AND_TIME" value="6"/>
    <eLiterals name="INT" value="7"/>
    <eLiterals name="SINT" value="8"/>
    <eLiterals name="LWORD" value="9"/>
    <eLiterals name="COLOR" value="10"/>
    <eLiterals name="WORD" value="11"/>
    <eLiterals name="REAL" value="12"/>
    <eLiterals name="TIME" value="13"/>
    <eLiterals name="TOD" value="14"/>
    <eLiterals name="ANY" value="15"/>
    <eLiterals name="DWORD" value="16"/>
    <eLiterals name="UDINT" value="17"/>
    <eLiterals name="USINT" value="18"/>
    <eLiterals name="TIME_OF_DAY" value="19"/>
    <eLiterals name="WSTRING" value="20"/>
    <eLiterals name="DINT" value="21"/>
    <eLiterals name="DATE" value="22"/>
    <eLiterals name="ULINT" value="23"/>
    <eLiterals name="VSTYLE" value="24"/>
    <eLiterals name="ARRAY" value="25"/>
    <eLiterals name="STRING" value="26"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlock" lowerBound="1"
        eType="#//FunctionBlock" containment="true" eOpposite="#//FunctionBlock/parentInterface"/>
  </eClassifiers>
</ecore:EPackage>
