<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cakefeed"
    nsURI="http://kieler.cs.cau.de/cakefeed/" nsPrefix="cakefeed">
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Identifiable #//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" lowerBound="1"
        upperBound="-1" eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationDomain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organisation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBNetwork" lowerBound="1"
        eType="#//FBNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBs" upperBound="-1" eType="#//FB"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventConnections" upperBound="-1"
        eType="#//EventConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataConnections" upperBound="-1"
        eType="#//DataConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapterConnections" upperBound="-1"
        eType="#//AdapterConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBNetwork" eType="#//FBNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DeviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SegmentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commResource" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segmentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FB" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//FBType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//FBInputEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEvents" upperBound="-1"
        eType="#//FBOutputEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputVars" upperBound="-1"
        eType="#//FBInputVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVars" upperBound="-1"
        eType="#//FBOutputVar" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputEvents" upperBound="-1"
        eType="#//IFInputEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputEvents" upperBound="-1"
        eType="#//IFOutputEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputVars" upperBound="-1"
        eType="#//IFInputVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputVars" upperBound="-1"
        eType="#//IFOutputVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sockets" upperBound="-1"
        eType="#//Adapter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plugs" upperBound="-1"
        eType="#//Adapter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBNetwork" eType="#//FBNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SegmentType">
    <eLiterals name="LocalHost"/>
    <eLiterals name="LocalBus" value="1"/>
    <eLiterals name="Ethernet" value="2"/>
    <eLiterals name="DeviceNet" value="3"/>
    <eLiterals name="ControlNet" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBType" abstract="true" eSuperTypes="#//Compilable #//NamedAndCommented #//FBInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventConnection" abstract="true" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataConnection" abstract="true" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompilerInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilers" upperBound="-1"
        eType="#//Compiler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classdef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFIFEventConnection" eSuperTypes="#//EventConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//IFOutputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IFInputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFIFDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//IFOutputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IFInputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFFBEventConnection" eSuperTypes="#//EventConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//FBInputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IFInputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFFBDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//FBInputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IFInputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBIFEventConnection" eSuperTypes="#//EventConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//IFOutputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FBOutputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBIFDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//IFOutputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FBOutputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBFBEventConnection" eSuperTypes="#//EventConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//FBInputEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FBOutputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBFBDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//FBInputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FBOutputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFIVDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//InternalVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IFInputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVIFDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//IFOutputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//InternalVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBIVDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//InternalVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FBOutputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVFBDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//FBInputVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//InternalVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IVIVDataConnection" eSuperTypes="#//DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//InternalVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//InternalVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterConnection" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFInputEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="with" upperBound="-1" eType="#//InputWith"
        containment="true" eOpposite="#//InputWith/parentInputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBInputEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="IFOutputEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="with" upperBound="-1" eType="#//OutputWith"
        containment="true" eOpposite="#//OutputWith/parentOutputEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBOutputEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Var" abstract="true" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arraySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VarType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFInputVar" eSuperTypes="#//Var"/>
  <eClassifiers xsi:type="ecore:EClass" name="FBInputVar" eSuperTypes="#//Var"/>
  <eClassifiers xsi:type="ecore:EClass" name="IFOutputVar" eSuperTypes="#//Var"/>
  <eClassifiers xsi:type="ecore:EClass" name="FBOutputVar" eSuperTypes="#//Var"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalVar" eSuperTypes="#//Var"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compiler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="product" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="Java"/>
    <eLiterals name="Cpp" value="1"/>
    <eLiterals name="C" value="2"/>
    <eLiterals name="Other" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="With" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputWith" eSuperTypes="#//With">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentInputEvent" lowerBound="1"
        eType="#//IFInputEvent" eOpposite="#//IFInputEvent/with"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="with" lowerBound="1" eType="#//IFInputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputWith" eSuperTypes="#//With">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentOutputEvent" lowerBound="1"
        eType="#//IFOutputEvent" eOpposite="#//IFOutputEvent/with"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="with" lowerBound="1" eType="#//IFOutputVar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VarType">
    <eLiterals name="BYTE"/>
    <eLiterals name="DT" value="1"/>
    <eLiterals name="LREAL" value="2"/>
    <eLiterals name="UINT" value="3"/>
    <eLiterals name="LINT" value="4"/>
    <eLiterals name="BOOL" value="5"/>
    <eLiterals name="DATE_AND_TIME" value="6"/>
    <eLiterals name="INT" value="7"/>
    <eLiterals name="SINT" value="8"/>
    <eLiterals name="LWORD" value="9"/>
    <eLiterals name="COLOR" value="10"/>
    <eLiterals name="WORD" value="11"/>
    <eLiterals name="REAL" value="12"/>
    <eLiterals name="TIME" value="13"/>
    <eLiterals name="TOD" value="14"/>
    <eLiterals name="ANY" value="15"/>
    <eLiterals name="DWORD" value="16"/>
    <eLiterals name="UDINT" value="17"/>
    <eLiterals name="USINT" value="18"/>
    <eLiterals name="TIME_OF_DAY" value="19"/>
    <eLiterals name="WSTRING" value="20"/>
    <eLiterals name="DINT" value="21"/>
    <eLiterals name="DATE" value="22"/>
    <eLiterals name="ULINT" value="23"/>
    <eLiterals name="VSTYLE" value="24"/>
    <eLiterals name="ARRAY" value="25"/>
    <eLiterals name="STRING" value="26"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter" abstract="true" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//AdapterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Socket" eSuperTypes="#//Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plug" eSuperTypes="#//Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterType" eSuperTypes="#//Compilable #//NamedAndCommented #//FBInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceSequences" lowerBound="1"
        upperBound="-1" eType="#//ServiceSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightInterface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftInterface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSequence" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceTransactions" upperBound="-1"
        eType="#//ServiceTransaction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTransaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPrimitive" eType="#//InputPrimitive"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPrimitives" upperBound="-1"
        eType="#//OutputPrimitive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPrimitive" eSuperTypes="#//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPrimitive" eSuperTypes="#//Primitive"/>
  <eClassifiers xsi:type="ecore:EClass" name="BFBType" eSuperTypes="#//FBType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syncChart" eType="ecore:EClass ../../de.cau.cs.kieler.synccharts/model/synccharts.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalVars" upperBound="-1"
        eType="#//InternalVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionBlockDiagrams"
        upperBound="-1" eType="#//FBD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sTs" upperBound="-1" eType="#//ST"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ladderDiagrams" upperBound="-1"
        eType="#//LD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherAlgorithms" upperBound="-1"
        eType="#//Other" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBD" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBs" lowerBound="1" upperBound="-1"
        eType="#//FB" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataConnections" upperBound="-1"
        eType="#//FBFBDataConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ST" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LD" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rungs" lowerBound="1" upperBound="-1"
        eType="#//Rung" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Other" eSuperTypes="#//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prototype" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rung">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CFBType" eSuperTypes="#//FBType #//FBNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//Service"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceType" eSuperTypes="#//Compilable #//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDeclarations" upperBound="-1"
        eType="#//InternalVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBNetwork" eType="#//FBNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceType" eSuperTypes="#//Compilable #//NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varDeclarations" upperBound="-1"
        eType="#//InternalVar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fBNetwork" lowerBound="1"
        eType="#//FBNetwork"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fBNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BFBDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bFBType" lowerBound="1"
        eType="#//BFBType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CFBDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cFBType" lowerBound="1"
        eType="#//CFBType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedAndCommented">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identification" eType="#//Identification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionInfos" lowerBound="1"
        upperBound="-1" eType="#//VersionInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compilable" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compilerInfo" eType="#//CompilerInfo"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
