<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devicetype"
    nsURI="http://kieler.cs.cau.de/cakefeed/devicetype" nsPrefix="devicetype">
  <eClassifiers xsi:type="ecore:EClass" name="DeviceType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Identification" eType="ecore:EClass system.ecore#//Identification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VersionInfo" lowerBound="1"
        upperBound="-1" eType="ecore:EClass system.ecore#//VersionInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CompilerInfo" eType="ecore:EClass system.ecore#//CompilerInfo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarDeclaration" upperBound="-1"
        eType="ecore:EClass system.ecore#//VarDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceName" upperBound="-1"
        eType="#//ResourceName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" upperBound="-1"
        eType="ecore:EClass system.ecore#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FBNetwork" eType="ecore:EClass system.ecore#//FBNetwork"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
