<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="system"
    nsURI="http://kieler.cs.cau.de/cakefeed/system" nsPrefix="system">
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Identification" eType="#//Identification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VersionInfo" lowerBound="1"
        upperBound="-1" eType="#//VersionInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Application" upperBound="-1"
        eType="#//Application" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Device" lowerBound="1"
        upperBound="-1" eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mapping" upperBound="-1"
        eType="#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Segment" upperBound="-1"
        eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" upperBound="-1" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ApplicationDomain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Classification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Function" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Standard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Organisation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FBNetwork" lowerBound="1"
        eType="#//FBNetwork" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FB" upperBound="-1" eType="#//FB"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventConnections" eType="#//EventConnections"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataConnections" eType="#//DataConnections"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AdapterConnections" eType="#//AdapterConnections"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FBNetwork" eType="#//FBNetwork"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="ecore:EClass deviceType.ecore#//DeviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="To" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" lowerBound="1" eType="#//SegmentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link"/>
  <eClassifiers xsi:type="ecore:EClass" name="FB">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="#//FBType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventConnections">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Connection" lowerBound="1"
        upperBound="-1" eType="#//EventConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConnections">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Connection" lowerBound="1"
        upperBound="-1" eType="#//DataConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterConnections">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Connection" lowerBound="1"
        upperBound="-1" eType="#//Connection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FBNetwork" eType="#//FBNetwork"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="ecore:EClass resourcetype.ecore#//ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SegmentType">
    <eLiterals name="LocalHost"/>
    <eLiterals name="LocalBus" value="1"/>
    <eLiterals name="Ethernet" value="2"/>
    <eLiterals name="DeviceNet" value="3"/>
    <eLiterals name="ControlNet" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FBType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Identification" eType="#//Identification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VersionInfo" lowerBound="1"
        upperBound="-1" eType="#//VersionInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CompilerInfo" eType="#//CompilerInfo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InterfaceList" lowerBound="1"
        eType="#//InterfaceList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilerInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Compiler" upperBound="-1"
        eType="#//Compiler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classdef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventInputs" eType="#//EventInputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EventOutputs" eType="#//EventOutputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InputVars" eType="#//InputVars"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutputVars" eType="#//OutputVars"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sockets" eType="#//Sockets"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Plugs" eType="#//Plugs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Destination" lowerBound="1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" lowerBound="1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConnection" eSuperTypes="#//Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Destination" lowerBound="1"
        eType="#//VarDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" lowerBound="1"
        eType="#//VarDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="With" upperBound="-1" eType="#//InputWith"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="With" upperBound="-1" eType="#//OutputWith"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ArraySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InitialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" lowerBound="1" eType="#//VarType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputVarDeclaration" eSuperTypes="#//VarDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputVarDeclaration" eSuperTypes="#//VarDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compiler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Language" lowerBound="1"
        eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Product" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vendor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="Java"/>
    <eLiterals name="Cpp" value="1"/>
    <eLiterals name="C" value="2"/>
    <eLiterals name="Other" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventInputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" lowerBound="1" upperBound="-1"
        eType="#//InputEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventOutputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Event" lowerBound="1" upperBound="-1"
        eType="#//OutputEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputVars">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarDeclaration" lowerBound="1"
        upperBound="-1" eType="#//InputVarDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputVars">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarDeclaration" lowerBound="1"
        upperBound="-1" eType="#//OutputVarDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sockets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AdapterDeclaration" lowerBound="1"
        upperBound="-1" eType="#//AdapterDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AdapterDeclaration" lowerBound="1"
        upperBound="-1" eType="#//AdapterDeclaration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="With"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputWith" eSuperTypes="#//With">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" lowerBound="1" eType="#//InputVarDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputWith" eSuperTypes="#//With">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Var" lowerBound="1" eType="#//OutputVarDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VarType">
    <eLiterals name="BYTE"/>
    <eLiterals name="DT" value="1"/>
    <eLiterals name="LREAL" value="2"/>
    <eLiterals name="UINT" value="3"/>
    <eLiterals name="LINT" value="4"/>
    <eLiterals name="BOOL" value="5"/>
    <eLiterals name="DATE_AND_TIME" value="6"/>
    <eLiterals name="INT" value="7"/>
    <eLiterals name="SINT" value="8"/>
    <eLiterals name="LWORD" value="9"/>
    <eLiterals name="COLOR" value="10"/>
    <eLiterals name="WORD" value="11"/>
    <eLiterals name="REAL" value="12"/>
    <eLiterals name="TIME" value="13"/>
    <eLiterals name="TOD" value="14"/>
    <eLiterals name="ANY" value="15"/>
    <eLiterals name="DWORD" value="16"/>
    <eLiterals name="UDINT" value="17"/>
    <eLiterals name="USINT" value="18"/>
    <eLiterals name="TIME_OF_DAY" value="19"/>
    <eLiterals name="WSTRING" value="20"/>
    <eLiterals name="DINT" value="21"/>
    <eLiterals name="DATE" value="22"/>
    <eLiterals name="ULINT" value="23"/>
    <eLiterals name="VSTYLE" value="24"/>
    <eLiterals name="ARRAY" value="25"/>
    <eLiterals name="STRING" value="26"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="ecore:EClass adaptertype.ecore#//AdapterType"/>
  </eClassifiers>
</ecore:EPackage>
