<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kit" nsURI="http://kieler.cs.cau.de/kit" nsPrefix="kit">
  <eClassifiers xsi:type="ecore:EClass" name="Statechart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iodeclarations" ordered="false" upperBound="-1" eType="//IoDeclaration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false" upperBound="-1" eType="//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="//ChartArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartArgument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IoDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" ordered="false" eType="//VType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="//DeclType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclType"/>
  <eClassifiers xsi:type="ecore:EClass" name="VType"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="//StateArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false" upperBound="-1" eType="//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="//Pseudo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" ordered="false" upperBound="-1" eType="//TransArgument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransArgument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" ordered="false" eType="//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="//TransType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prio" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="weakabortion" eSuperTypes="//TransType"/>
  <eClassifiers xsi:type="ecore:EClass" name="strongabortion" eSuperTypes="//TransType"/>
  <eClassifiers xsi:type="ecore:EClass" name="normaltermination" eSuperTypes="//TransType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" ordered="false" upperBound="-1" eType="//Emission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" ordered="false" eType="//Trigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Emission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" ordered="false" eType="//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" ordered="false" eType="//Signal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInput" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false" eType="//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOutput" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTrigger" ordered="false" upperBound="-1" eType="//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" ordered="false" upperBound="-1" eType="//BinaryOp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" ordered="false" upperBound="-1" eType="//Signal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOp"/>
</ecore:EPackage>
