/*
* generated by Xtext
*/
package de.cau.cs.kieler.xtext.contentassist;

import de.cau.cs.kieler.xtext.contentassist.AbstractExampleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExampleProposalProvider extends AbstractExampleProposalProvider {

}
