  


/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;



public interface EMFModelObject {
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.ModelObject getEMFObject();
}