

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;


import org.eclipse.gmt.gems.model.Atom;
import org.eclipse.gmt.gems.model.Model;
import org.eclipse.gmt.gems.model.Visitor;

/**
 * 
 */
 
public interface MealyMachineVisitor extends Visitor{
    public static final String MODEL_ID = "http://www.informatik.uni-kiel.de/rtsys/gems/mealy";
    
	
	


	   public void visitMealyMachine(MealyMachine tovisit);
	 
	   public void visitState(State tovisit);
	 
}

