

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;

import org.eclipse.gmt.gems.Memento;

public class MementoImpl implements Memento {

	private de.cau.cs.kieler.gems.mealy.emf.mealymachine.Memento model_;
	
	public MementoImpl(){		
	}
	
	public MementoImpl(de.cau.cs.kieler.gems.mealy.emf.mealymachine.Memento model){
		model_ = model;
	}
	
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.Memento getModel(){
		if(model_ == null){
			model_ = de.cau.cs.kieler.gems.mealy.emf.mealymachine.impl.MealyMachineFactoryImpl.eINSTANCE.createMemento();
		}
		return model_;
	}
	public void setId(String id){
		getModel().setId(id);
	}
	
	public String getId(){
		return getModel().getId();
	}
	
	public void setValue(String name, String value){
		de.cau.cs.kieler.gems.mealy.emf.mealymachine.MementoValue mv = de.cau.cs.kieler.gems.mealy.emf.mealymachine.impl.MealyMachineFactoryImpl.eINSTANCE.createMementoValue();
		mv.setName(name);
		mv.setValue(value);
		getModel().getData().add(mv);
	}
	public String getValue(String name){
		for(Object curr : getModel().getData()){
			de.cau.cs.kieler.gems.mealy.emf.mealymachine.MementoValue mv = (de.cau.cs.kieler.gems.mealy.emf.mealymachine.MementoValue)curr;
			if(mv.getName().equals(name)){
				return mv.getValue();
			}
		}
		return null;
	}
    
}

