

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package edu.unikiel.rtsys.gems.mealy.mealymachine;



import org.eclipse.gmt.gems.metamodel.gen.AttributeInfo;
import org.eclipse.gmt.gems.model.AttributeValidator;
import org.eclipse.gmt.gems.ModelProvider;
import org.eclipse.gmt.gems.ModelRepository;
import org.eclipse.gmt.gems.model.Visitor;
import org.eclipse.gmt.gems.model.ConnectionType;
import org.eclipse.gmt.gems.model.Wire;
import org.eclipse.ui.views.properties.IPropertyDescriptor;

import java.util.Vector;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.gmt.gems.model.LogicElement;
import java.util.List;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Point;
import org.eclipse.gmt.gems.model.ModelUtilities;
import org.eclipse.gmt.gems.model.props.CustomProperty;
import org.eclipse.gmt.gems.model.props.CustomPropertyEx;
import org.eclipse.gmt.gems.model.props.PropertyRepository;
import org.eclipse.emf.ecore.EObject;

import de.cau.cs.kieler.gems.mealy.emf.mealymachine.*;

public class State extends org.eclipse.gmt.gems.model.LinkedModel  implements Adapter, EMFModelObject, org.eclipse.gmt.gems.model.EMFModelElement{

	private de.cau.cs.kieler.gems.mealy.emf.mealymachine.State model_;
	private Notifier target_;
	
	public State(){		
	}
	
	public State(de.cau.cs.kieler.gems.mealy.emf.mealymachine.State model){
		model_ = model;
		super.setName(model_.getName());
		super.setID(model_.getId());
    	model_.eAdapters().add(this);
	}
	
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.State getModel(){
		if(model_ == null){
			model_ = de.cau.cs.kieler.gems.mealy.emf.mealymachine.impl.MealyMachineFactoryImpl.eINSTANCE.createState();
			super.setName(model_.getName());
			model_.eAdapters().add(this);
		}
		return model_;
	}
	
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.State getExtendedModel(){
		return getModel();
	}
	
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.State getEMFObject(){
		return getModel();
	}
	
       
    public String getName(){
    	return getExtendedModel().getName();
    }
    
    public boolean isVisible(){
    	return getExtendedModel().isVisible();
    }
    
    
    public void setVisible(boolean b){
    	getExtendedModel().setVisible(b);
    	super.setVisible(b);
    }
    
    public void setName(String name){
    	getExtendedModel().setName(name);
    	super.setName(name);
    }
    
    public String getID(){
    	return getExtendedModel().getId();
    }
    
    public boolean isSubtype(){
    	return getExtendedModel().isSubtype();
    }
    
    public void setSubtype(boolean b){
    	getExtendedModel().setSubtype(b);
    	super.setSubtype(b);
    }
    
    public void setID(String id){
    	getExtendedModel().setId(id);
    	super.setID(id);
    }
    
    public Point getLocation(){
    	return new Point(getExtendedModel().getX(),getExtendedModel().getY());
    }
    
    public void setLocation(Point p) {
    	getExtendedModel().setX(p.x);
    	getExtendedModel().setY(p.y);
        super.setLocation(p);
    }
    
    public Dimension getSize() {
        return new Dimension(getExtendedModel().getWidth(),getExtendedModel().getHeight());
    }
    
    public org.eclipse.gmt.gems.Subtype createSubtype(){
    	return new EMFSubtypeImpl(this,getName());
    }
    
    public void setSize(Dimension d){
    	getExtendedModel().setWidth(d.width);
    	getExtendedModel().setHeight(d.height);
    	super.setSize(d);
    }
    
    public EObject getEMFModelElement(){
    	return getEMFObject();
    }
    
    public String getModelLinkTarget(){
    	return getExtendedModel().getModelLinkTarget();
    }
    
    public void setModelLinkTarget(String target){
    	getExtendedModel().setModelLinkTarget(target);
 		super.setModelLinkTarget(target);
    }
    	
    	public Notifier getTarget() {
    		return target_;
    	}
    	
    	public void setTarget(Notifier newTarget) {
    		target_ = newTarget;
    	}
    	
    	public boolean isAdapterForType(Object type) {
    		return getModel() == type;
    	}
    
    
    

    public static final IPropertyDescriptor[] STATE_ATTRIBUTE_DESCRIPTORS =
    {
new org.eclipse.ui.views.properties.TextPropertyDescriptor("StateName","StateName")


    };
    public static final Object[] STATE_DEFAULT_ATTRIBUTE_VALUES = {
       
            "0"
    };
    
      	 

    
    protected void getPropertyDescriptors(Vector desc){
    	desc.addAll(java.util.Arrays.asList(STATE_ATTRIBUTE_DESCRIPTORS));    	
    	super.getPropertyDescriptors(desc);
    }
    
   
    	
    	private String StateName_ = "0";
    public String findAttributeType(String attr){
      if(attr.equals("StateName")){
        return STRING_MTYPE;
      }
      return super.findAttributeType(attr);
    }
   public String getStateName(){
   	return getModel().getStateName();
   	
   }
   public void setStateName(String val){
     Object old = getStateName();
   	 getModel().setStateName(val);
   	 
   	  Object[] valuepair = {"StateName",old};        
      org.eclipse.gmt.gems.model.event.ModelChangeEvent event = new org.eclipse.gmt.gems.model.event.ModelChangeEvent(this,
                org.eclipse.gmt.gems.model.event.ModelChangeEvent.ELEMENT_ATTRIBUTE_CHANGED,false,(Object)valuepair);
      org.eclipse.gmt.gems.model.event.ModelEventDispatcher.dispatch(event);
      
      if(event.vetoed()){
      	setStateName((String)old);
      }
   }
    public Object getAttribute(String attr){
    	
	 if(attr != null &&
	    attr.equals("StateName")){
	    return getStateName().toString();
	  }
     return super.getAttribute(attr);
   }
  
   
    public void setAttribute(String attr, Object val){
         if(attr != null){
           AttributeValidator validator = AttributeValidators.getInstance().getValidator(attr);
           if(validator != null &&
              !validator.validValue(this,attr,val)){
                return;
              }
         }	
         if(attr.equals(org.eclipse.gmt.gems.model.Atom.NAME)){
        	 getModel().setName((String)val);
         }   													
	 if(attr != null &&
	    attr.equals("StateName")){
	    setStateName(new String((String)val));
	  }
      else {
        super.setAttribute(attr,val); }
   }
   
   public void notifyChanged(Notification notification) {
   		int type = notification.getEventType();
   		int featureId = notification.getFeatureID(MealyMachinePackage.class);
    		
   		switch(type) {
   		case Notification.SET:
   		
   			switch(featureId) {
    			case MealyMachinePackage.STATE__STATE_NAME :
   				firePropertyChange(ATTRIBUTE_PREFIX+"StateName", notification.getOldStringValue(), notification.getNewStringValue());
   				break;
   			}
   	    
   		case Notification.ADD:
   		case Notification.REMOVE:
   		}
   }
   
    

	
	public List<State> getOutgoingTransitions(){
		return (List<State>)ModelUtilities.getConnectedTargets(this,State.class,TransitionConnectionType.INSTANCE);
	}
	
	
		
	public List<State> getIncomingTransitions(){
		return (List<State>)ModelUtilities.getConnectedSources(this,State.class,TransitionConnectionType.INSTANCE);
	}
	

@Override
public void connectOutput(Wire w) {
	
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
	
			edu.unikiel.rtsys.gems.mealy.mealymachine.Root r = (edu.unikiel.rtsys.gems.mealy.mealymachine.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getModelInstanceID()).getRoot();
			if(r != null)
				r.addConnection(w);
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
			if(con != null){
				con.setSource(getModel());
				
					getModel().getOutgoingTransitions().add(con);
				
			}
		
      }
	
	}
	super.connectOutput(w);
}

@Override
public void connectInput(Wire w) {

	ConnectionType type = w.getConnectionType();
	if(type != null){
	
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
	
	        edu.unikiel.rtsys.gems.mealy.mealymachine.Root r = (edu.unikiel.rtsys.gems.mealy.mealymachine.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getModelInstanceID()).getRoot();
			if(r != null)
				r.addConnection(w);
	
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
			if(con != null){
				con.setTarget(getModel());
				
					getModel().getIncomingTransitions().add(con);
				
			}
		
    }
	
	}
	super.connectInput(w);
}

@Override
public void disconnectInput(Wire w) {
	
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
	
	        ((edu.unikiel.rtsys.gems.mealy.mealymachine.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getModelInstanceID()).getRoot()).removeConnection(w);
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
			if(con != null){
				con.setTarget(null);
				
					getModel().getIncomingTransitions().remove(con);
				
			}
		
    }
	
	}
	super.disconnectInput(w);
}


@Override
public void disconnectOutput(Wire w) {
	
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
		    ((edu.unikiel.rtsys.gems.mealy.mealymachine.Root)ModelRepository.getInstance().getInstanceRepository().getInstance(getModelInstanceID()).getRoot()).removeConnection(w);
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
		
			if(con != null){
				con.setSource(null);
				
					getModel().getOutgoingTransitions().remove(con);
				
			}
		
    }
	
	}
	super.disconnectOutput(w);
}


public void connectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectInput(w);
	else
		connectInput(w);
}

public void disconnectInput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectInput(w);
	else
		disconnectInput(w);
}



public void connectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.connectOutput(w);
	else
		connectOutput(w);
}

public void disconnectOutput(Wire w, boolean modifymodel) {
	if(!modifymodel)
		super.disconnectOutput(w);
	else
		disconnectOutput(w);
}



    
    
    public String getConnectionRole(ConnectionType ct, boolean src){
		
	    if(ct instanceof TransitionConnectionType && src){
	       return "OutgoingTransitions";
	    }
	
	    if(ct instanceof TransitionConnectionType && !src){
	       return "IncomingTransitions";
	    }
	
	  return super.getConnectionRole(ct,src);
	}
	
	public List<String> getRelationshipRoles(){
    	java.util.List<String> roles = super.getRelationshipRoles();
    		
	   roles.add("OutgoingTransitions");
	
	    roles.add("IncomingTransitions");
	
    	return roles;
    }
	
	
	public ConnectionType getConnectionTypeForRole(String role){
		
	    if("OutgoingTransitions".equalsIgnoreCase(role)){
	       return TransitionConnectionType.INSTANCE;
	    }
	
	    if("IncomingTransitions".equalsIgnoreCase(role)){
	       return TransitionConnectionType.INSTANCE;
	    }
	
	  return super.getConnectionTypeForRole(role);
	}
	
    public Object getRoleValue(String role){
		
	    if("OutgoingTransitions".equalsIgnoreCase(role)){
	       return getOutgoingTransitions();
	    }
	
	    if("IncomingTransitions".equalsIgnoreCase(role)){
	       return getIncomingTransitions();
	    }
	
	
		if("ParentMachine".equalsIgnoreCase(role)){
	       return getParentMachine();
	    }
	
	
	  return super.getRoleValue(role);
	}
	
	
	public MealyMachine getParentMachine(){
	       if(getParent() instanceof MealyMachine){
	       	  return (MealyMachine)getParent();
	       }
	       return null;
	}
	
    
    public boolean isAbstract(){return false;}
     
    public ModelProvider getModelProvider() {
        ModelProvider provider = super.getModelProvider();
        if(provider == null){
        	provider = new MealyMachineProvider();
        	ModelRepository.getInstance().registerModelProvider(provider);
        }
        return provider;
    }
    
    protected void buildContainmentNames() {
    }
    
    	public List<String> getContainmentRoles(){
    	List<String> roles = super.getContainmentRoles();
    	
    	roles.add("ParentMachine");
    	
    	return roles;
    }
    
    public Class getParentForRole(String role){
    	
    	if("ParentMachine".equals(role)){
    		return MealyMachine.class;
    	}
    	
    	return super.getParentForRole(role);
    }
    
    public String getRoleForParent(Class c){
    	
    	if(MealyMachine.class.isAssignableFrom(c)){
    	   return "ParentMachine";
    	}
    	
    	return super.getRoleForParent(c);
    }	
    
public void accept(Visitor visitor) {
   if(visitor instanceof MealyMachineVisitor)
   	((MealyMachineVisitor)visitor).visitState(this);
   else
     super.accept(visitor);
}
   
    
    public void addChild(LogicElement child, int index) {
       addChild(child,index,true);
    }
    
    public void addChild(LogicElement child, int index, boolean modifymodel) {
       	if(modifymodel){
    	}
    	
    	super.addChild(child,index);
    	
    }
    
    public void removeChild(LogicElement child){
		removeChild(child,true);
    }
    
    public void removeChild(LogicElement child, boolean modifymodel){
    	if(modifymodel){
     	
    	}
    	
    		super.removeChild(child);
    	
    }
    
    
    public boolean isExpanded(){
    	return getExtendedModel().isExpanded();
    }
    
    public void setExpanded(boolean ex){
    	getExtendedModel().setExpanded(ex);
    	super.setExpanded(ex);
    }
    
    public Dimension getExpandSize() {
        return new Dimension(getModel().getExpandedWidth(),getModel().getExpandedHeight());
    }
    
    public void setExpandSize(Dimension d){
    	getExtendedModel().setExpandedWidth(d.width);
    	getExtendedModel().setExpandedHeight(d.height);
    	super.setExpandSize(d);
    }
    
    public void setAnnotation(String a){
       getExtendedModel().setAnnotation(a);
       super.setAnnotation(a);
    }
    
    public String getAnnotation(){
      return getExtendedModel().getAnnotation();
    }
    
    public String getModelID() {
        return MealyMachineProvider.MODEL_ID;
    }
    

}

