<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ssm2dl" nsURI="http://www.informatik.uni-kiel.de/rtsys/ssm2/dsl" nsPrefix="ssm2dl"/>
