<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="KimlLayoutGraph"
    nsURI="http://www.informatik.uni-kiel.de/rtsys/kimllayoutgraph" nsPrefix="kimllayoutgraph">
  <eClassifiers xsi:type="ecore:EClass" name="KPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KInsets">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topGroup" lowerBound="1"
        eType="#//KNodeGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KShapeLayout" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//KDimension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useLayout" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//KNodeGroup" eOpposite="#//KNodeGroup/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//KNodeGroup" eOpposite="#//KNodeGroup/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KEdgeLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" upperBound="-1"
        eType="#//KEdgeLabel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" eType="#//KPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" eType="#//KPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePoint" lowerBound="1"
        eType="#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPoint" lowerBound="1"
        eType="#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gridPoints" upperBound="-1"
        eType="#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeType" lowerBound="1"
        eType="#//EDGE_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useLayout" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subNodeGroups" upperBound="-1"
        eType="#//KNodeGroup" eOpposite="#//KNodeGroup/parentGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//KEdge" eOpposite="#//KEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//KEdge" eOpposite="#//KEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentGroup" lowerBound="1"
        eType="#//KNodeGroup" eOpposite="#//KNodeGroup/subNodeGroups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KNodeGroupLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="#//KNodeGroupLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idString" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//KPort" eOpposite="#//KPort/nodeGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeGroupLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutType" lowerBound="1"
        eType="#//LAYOUT_TYPE" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutOptions" ordered="false"
        upperBound="-1" eType="#//LAYOUT_OPTION" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterName" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insets" lowerBound="1"
        eType="#//KInsets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLabel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" lowerBound="1"
        eType="#//KEdgeLabelLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLabelLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPlacement" lowerBound="1"
        eType="#//EDGE_LABEL_PLACEMENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeGroupLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" lowerBound="1"
        eType="#//KNodeGroupLabelLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeGroupLabelLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPlacement" lowerBound="1"
        eType="#//NODE_LABEL_PLACEMENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDGE_TYPE">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="DIRECT" value="1" literal="Direct"/>
    <eLiterals name="SPLINE" value="2" literal="Spline"/>
    <eLiterals name="BEZIER" value="3" literal="Bezier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LAYOUT_TYPE">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="PATTERN_RECOGNITION" value="1" literal="Pattern recognition"/>
    <eLiterals name="HIERARCHICAL" value="2" literal="Hierarchical"/>
    <eLiterals name="CIRCLE" value="3" literal="Circle"/>
    <eLiterals name="RADIAL" value="4" literal="Radial"/>
    <eLiterals name="SPRING_MODEL" value="5" literal="Spring model"/>
    <eLiterals name="OTHER" value="6" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LAYOUT_OPTION">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="PRESERVE_MENTAL_MAP" value="1" literal="Preserve mental map"/>
    <eLiterals name="VERTICAL" value="2" literal="Vertical"/>
    <eLiterals name="HORIZONTAL" value="3" literal="Horizontal"/>
    <eLiterals name="FIXED_PORTS" value="4" literal="Fixed ports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDGE_LABEL_PLACEMENT">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="CENTER" value="1" literal="CENTER"/>
    <eLiterals name="HEAD" value="2"/>
    <eLiterals name="TAIL" value="4"/>
    <eLiterals name="LEFT" value="8"/>
    <eLiterals name="RIGHT" value="16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NODE_LABEL_PLACEMENT">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="INSIDE_NORTH" value="1"/>
    <eLiterals name="INSIDE_SOUTH" value="2"/>
    <eLiterals name="INSIDE_WEST" value="3" literal="INSIDE_WEST"/>
    <eLiterals name="INSIDE_EAST" value="4"/>
    <eLiterals name="OUTSIDE_NORTH" value="5"/>
    <eLiterals name="OUTSIDE_SOUTH" value="6" literal="OUTSIDE_SOUTH"/>
    <eLiterals name="OUTSIDE_WEST" value="7"/>
    <eLiterals name="OUTSIDE_EAST" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LAYOUTER_INFO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterName" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutType" lowerBound="1"
        eType="#//LAYOUT_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutOption" lowerBound="1"
        eType="#//LAYOUT_OPTION"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterCollectionID" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KPortLayout"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//KPortLabel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeGroup" lowerBound="1"
        eType="#//KNodeGroup" eOpposite="#//KNodeGroup/ports"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PORT_TYPE"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//KEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placement" eType="#//PORT_PLACEMENT"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" eType="#//KPortLabelLayout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLabelLayout" eSuperTypes="#//KShapeLayout"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PORT_TYPE">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="INPUT" value="1" literal="Input"/>
    <eLiterals name="OUTPUT" value="2" literal="Output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PORT_PLACEMENT">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="NORTH" value="1" literal="North"/>
    <eLiterals name="EAST" value="2" literal="East"/>
    <eLiterals name="SOUTH" value="3" literal="South"/>
    <eLiterals name="WEST" value="4" literal="West"/>
  </eClassifiers>
</ecore:EPackage>
