/*
 * generated by Xtext
 */
package de.cau.cs.kieler.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExampleUiModule extends de.cau.cs.kieler.xtext.AbstractExampleUiModule {

}
