

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package edu.unikiel.rtsys.gems.mealy.mealymachine;

import org.eclipse.gmt.gems.LabelProvider;


public class LabelProviderImpl implements LabelProvider {

	/**
	 * 
	 */
	public LabelProviderImpl() {
		super();
		
	}

	/* (non-Javadoc)
	 * @see org.eclipse.gmt.gems.LabelProvider#getLabel(java.lang.Object)
	 */
	public String getLabel(Object key) {
		String name = key.getClass().getName();
		return key.getClass().getName().substring(name.lastIndexOf(".")+1);
	}

	/* (non-Javadoc)
	 * @see org.eclipse.gmt.gems.LabelProvider#getDescription(java.lang.Object)
	 */
	public String getDescription(Object key) {
		// TODO Auto-generated method stub
		return "";
	}

}
