/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package edu.unikiel.informatik.aiw.epc.validation;

import edu.unikiel.informatik.aiw.epc.EPCObject;
import edu.unikiel.informatik.aiw.epc.Relationship;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.unikiel.informatik.aiw.epc.EPC}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EPCValidator {
	boolean validate();

	boolean validateConnectors(EList<Relationship> value);
	boolean validateObjects(EList<EPCObject> value);
}
