<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epc"
    nsURI="http://informatik.uni-kiel.de/aiw/epcmodel" nsPrefix="epc">
  <eClassifiers xsi:type="ecore:EClass" name="EPC" eSuperTypes="#//Function">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Relationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//EPCObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="TriggersEvent" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalOperator" abstract="true" interface="true"
      eSuperTypes="#//EPCObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOR" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" interface="true"
      eSuperTypes="#//EPCObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPCObject" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showInEPCEditor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivatesFunction" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuccessorOf" abstract="true" interface="true"
      eSuperTypes="#//Relationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidesDataTo" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Application"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WritesDataTo" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionToOperatorConnection" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventToOperatorConnection" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorToFunctionConnection" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorToEventConnection" eSuperTypes="#//SuccessorOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//LogicalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GCTLconnector" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implication" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equivalence" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organisation" eSuperTypes="#//Node"/>
</ecore:EPackage>
