<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gctl"
    nsURI="http://informatik.uni-kiel.de/aiw/gctlmodel" nsPrefix="gctl">
  <eClassifiers xsi:type="ecore:EClass" name="GCTL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" eType="ecore:EClass epc.ecore#//Node"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
