<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="KimlLayoutGraph"
    nsURI="http://www.informatik.uni-kiel.de/rtsys/kimllayoutgraph" nsPrefix="kimllayoutgraph">
  <eClassifiers xsi:type="ecore:EClass" name="KPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KInsets">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutGraph" eSuperTypes="#//KLayoutNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphEdges" upperBound="-1"
        eType="#//KLayoutEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KShapeLayout" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//KPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//KDimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useLayout" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//KLayoutNode" eOpposite="#//KLayoutNode/outgoingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//KLayoutNode" eOpposite="#//KLayoutNode/incomingEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KEdgeLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" upperBound="-1"
        eType="#//KEdgeLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" eType="#//KLayoutPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" eType="#//KLayoutPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLayout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePoint" lowerBound="1"
        eType="#//KPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPoint" lowerBound="1"
        eType="#//KPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendPoints" upperBound="-1"
        eType="#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeType" lowerBound="1"
        eType="#//KEdgeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useLayout" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childNodes" upperBound="-1"
        eType="#//KLayoutNode" containment="true" eOpposite="#//KLayoutNode/parentNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEdges" upperBound="-1"
        eType="#//KLayoutEdge" eOpposite="#//KLayoutEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEdges" upperBound="-1"
        eType="#//KLayoutEdge" eOpposite="#//KLayoutEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" lowerBound="1"
        eType="#//KLayoutNode" eOpposite="#//KLayoutNode/childNodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KNodeLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="#//KNodeLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idString" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//KLayoutPort" containment="true" eOpposite="#//KLayoutPort/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutType" lowerBound="1"
        eType="#//KLayoutType" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutOptions" ordered="false"
        upperBound="-1" eType="#//KLayoutOption" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterName" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insets" lowerBound="1"
        eType="#//KInsets" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLabel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" lowerBound="1"
        eType="#//KEdgeLabelLayout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLabelLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPlacement" lowerBound="1"
        eType="#//KEdgeLabelPlacement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" lowerBound="1"
        eType="#//KNodeLabelLayout" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KNodeLabelLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPlacement" lowerBound="1"
        eType="#//KNodeLabelPlacement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KEdgeType">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="DIRECT" value="1" literal="Direct"/>
    <eLiterals name="SPLINE" value="2" literal="Spline"/>
    <eLiterals name="BEZIER" value="3" literal="Bezier"/>
    <eLiterals name="RECTILINEAR" value="4" literal="Rectilinear"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KLayoutType">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="ORTHOGONAL" value="1" literal="Orthogonal"/>
    <eLiterals name="HIERARCHICAL" value="2" literal="Hierarchical"/>
    <eLiterals name="CIRCLE" value="3" literal="Circle"/>
    <eLiterals name="RADIAL" value="4" literal="Radial"/>
    <eLiterals name="SPRING_MODEL" value="5" literal="Spring model"/>
    <eLiterals name="OTHER" value="6" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KLayoutOption">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="PRESERVE_MENTAL_MAP" value="1" literal="Preserve mental map"/>
    <eLiterals name="VERTICAL" value="2" literal="Vertical"/>
    <eLiterals name="HORIZONTAL" value="3" literal="Horizontal"/>
    <eLiterals name="FIXED_PORTS" value="4" literal="Fixed ports"/>
    <eLiterals name="FIXED_PORT_SIDES" value="5" literal="Fixed port sides"/>
    <eLiterals name="FIXED_SIZE" value="6" literal="Fixed size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KEdgeLabelPlacement">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="CENTER" value="1" literal="CENTER"/>
    <eLiterals name="HEAD" value="2"/>
    <eLiterals name="TAIL" value="4"/>
    <eLiterals name="LEFT" value="8"/>
    <eLiterals name="RIGHT" value="16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KNodeLabelPlacement">
    <eLiterals name="DEFAULT" literal="DEFAULT"/>
    <eLiterals name="INSIDE_NORTH" value="1"/>
    <eLiterals name="INSIDE_SOUTH" value="2"/>
    <eLiterals name="INSIDE_WEST" value="3" literal="INSIDE_WEST"/>
    <eLiterals name="INSIDE_EAST" value="4"/>
    <eLiterals name="OUTSIDE_NORTH" value="5"/>
    <eLiterals name="OUTSIDE_SOUTH" value="6" literal="OUTSIDE_SOUTH"/>
    <eLiterals name="OUTSIDE_WEST" value="7"/>
    <eLiterals name="OUTSIDE_EAST" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayouterInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterName" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutType" lowerBound="1"
        eType="#//KLayoutType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutOption" lowerBound="1"
        eType="#//KLayoutOption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layouterCollectionID" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutPort">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" lowerBound="1"
        eType="#//KPortLayout" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//KPortLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//KLayoutNode"
        eOpposite="#//KLayoutNode/ports"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//KPortType"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//KLayoutEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLayout" eSuperTypes="#//KShapeLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placement" eType="#//KPortPlacement"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLabel" eSuperTypes="#//KLabel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelLayout" eType="#//KPortLabelLayout"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPortLabelLayout" eSuperTypes="#//KShapeLayout"/>
  <eClassifiers xsi:type="ecore:EEnum" name="KPortType">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="INPUT" value="1" literal="Input"/>
    <eLiterals name="OUTPUT" value="2" literal="Output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="KPortPlacement">
    <eLiterals name="DEFAULT" literal="Default"/>
    <eLiterals name="NORTH" value="1" literal="North"/>
    <eLiterals name="EAST" value="2" literal="East"/>
    <eLiterals name="SOUTH" value="3" literal="South"/>
    <eLiterals name="WEST" value="4" literal="West"/>
  </eClassifiers>
</ecore:EPackage>
