

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;


import java.util.Hashtable;
import java.util.LinkedList;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.gmt.gems.model.Container;
import org.eclipse.gmt.gems.model.LinkedModel;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.gmt.gems.ModelInstance;
import org.eclipse.gmt.gems.ModelRepository;
import org.eclipse.gmt.gems.model.Wire;

public class GemsFactory{
	private Root root_;
	//private LinkedList conns_;
	private Hashtable<Object, ModelObject> parts_ = new Hashtable<Object, ModelObject>();;
	private LinkedList<Wire> wires_ = new LinkedList<Wire>();
	private LinkedList<Runnable> requests_ = new LinkedList<Runnable>();
	private Hashtable connected_ = new Hashtable();
	
	public ModelInstance loadModel(de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root root){
		Root groot = load(root);
		ModelInstance inst = ModelRepository.getInstance().getInstanceRepository().getInstance(groot.getModelInstanceID());
		inst.setRoot(groot);
		
		for(Runnable req : requests_)
			req.run();
		
		EList subts = root.getSubtypes();
    	for(Object obj : subts){
    		org.eclipse.gmt.gems.Subtype st = createSubtype((de.cau.cs.kieler.gems.mealy.emf.mealymachine.Subtype)obj);
    		inst.addSubType(st);
    	}
    	
    	return inst;
	}
	
	public void checkLinking(LinkedModel model){
		if(model.getModelLinkTarget() != null
		   && model.getModelLinkTarget().trim().length() > 0){
		   model.loadModel();  
		   map(model);
		}
	}
	
	public void map(ModelObject mo){
		if(mo instanceof EMFModelObject){
			EObject obj = ((EMFModelObject)mo).getEMFObject();
			String key = obj.eResource().getURI().toString()+"#"+mo.getID();
			parts_.put(key, mo);
		}
		if(mo instanceof Container){
			Container cont = (Container)mo;
			for(Object o : cont.getChildren()){
				if(o instanceof ModelObject){
					map((ModelObject)o);
				}
			}
		}
	}
	
	public Root load(de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root root){
		Root groot = new Root(root);
		//root_ = groot;
		//conns_ = new LinkedList();
		//wires_ = new LinkedList<Wire>();
		//parts_ = new Hashtable<Object, ModelObject>();
		
		parts_.put(root,groot);
		
		
		de.cau.cs.kieler.gems.mealy.emf.mealymachine.MealyMachine rrm = root.getRealRoot();
		if(rrm != null){
			MealyMachine rr = (MealyMachine)getPart(groot, rrm);
			groot.setRealRoot(rr);			
		}
		
		
		
    	EList mealymachine = root.getMealyMachine();
    	for(Object obj : mealymachine){
    		getPart(groot,obj);
    	}
    	
    	
    	EList state = root.getState();
    	for(Object obj : state){
    		getPart(groot,obj);
    	}
    	
    	
    	EList transitioncons = root.getTransitionConnection();
    	for(Object obj : transitioncons){
    		createTransitionConnection(groot, (de.cau.cs.kieler.gems.mealy.emf.mealymachine.TransitionConnection)obj);
    	} 
    	
    	
    	
    	
    	return groot;
	}
    
    public ModelObject load(Container root, Object child) {
    	if(child instanceof de.cau.cs.kieler.gems.mealy.emf.mealymachine.MealyMachine){
    		return loadMealyMachine(root,(de.cau.cs.kieler.gems.mealy.emf.mealymachine.MealyMachine)child);
    	}
    	
    	if(child instanceof de.cau.cs.kieler.gems.mealy.emf.mealymachine.State){
    		return loadState(root,(de.cau.cs.kieler.gems.mealy.emf.mealymachine.State)child);
    	}
    	
    	return null;
    }
    
    	public MealyMachine loadMealyMachine(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.MealyMachine obj){
    	   MealyMachine gobj = null;
    	   
    	   gobj = new MealyMachine(obj);  
    	   
    	   loadMealyMachine(root,obj,gobj);
    	   parts_.put(obj,gobj);
    	   if(obj.eResource() != null){
    	     parts_.put(obj.eResource().getURI().toString()+"#"+obj.getId(),gobj);
    	   }
    	   return gobj;
    	}
   	
    	public State loadState(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.State obj){
    	   State gobj = null;
    	   
    	   gobj = new State(obj);  
    	   
    	   loadState(root,obj,gobj);
    	   parts_.put(obj,gobj);
    	   if(obj.eResource() != null){
    	     parts_.put(obj.eResource().getURI().toString()+"#"+obj.getId(),gobj);
    	   }
    	   return gobj;
    	}
   	
   	
   	 
    	public MealyMachine loadMealyMachine(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.MealyMachine obj, MealyMachine gobj){
    	   
    	   if(root != null)
    	     root.addChild(gobj,-1,false);
    	   
    	
    	   
    	   
    		EList states = obj.getStates();
    		for(Object child : states){
    			loadState(gobj,(de.cau.cs.kieler.gems.mealy.emf.mealymachine.State)child);
    		}
    	   
    	   
    	   
    	   
    	   if(gobj instanceof LinkedModel){
    	   	  checkLinking((LinkedModel)gobj);
    	   }
    	   
    	   
    	   
    	   return gobj;
    	}
    	
    	
    	public State loadState(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.State obj, State gobj){
    	   
    	   if(root != null)
    	     root.addChild(gobj,-1,false);
    	   
    	
    	   
    	   
    	   
    	   
    	   
    	   if(gobj instanceof LinkedModel){
    	   	  checkLinking((LinkedModel)gobj);
    	   }
    	   
    	   
    	   addDeferredRequest(new StateConnector(root,obj,gobj));
    	   
    	   
    	   return gobj;
    	}
    	
    	
    	public class StateConnector implements Runnable {
    	  private Container root_;
    	  private de.cau.cs.kieler.gems.mealy.emf.mealymachine.State obj_;
    	  private State gobj_;
    	  
    	  public StateConnector(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.State obj, State gobj){
    	    root_ = root;
    	    obj_ = obj;
    	    gobj_ = gobj;
    	  }
    	  public void run(){
    		loadConnections(root_,obj_,gobj_);
    	  }
    	}
    	
    	public void loadConnections(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.State obj, State gobj){
    	
    	   
    	   
    	 }
    	
   	
   	
   	public org.eclipse.gmt.gems.Subtype createSubtype(de.cau.cs.kieler.gems.mealy.emf.mealymachine.Subtype subt){
   		ModelObject base = parts_.get(subt.getBase());
   		String name = subt.getName();
   		EMFSubtypeImpl esub = new EMFSubtypeImpl(base,subt,name);
   		for(Object obj : subt.getInstances()){
   			esub.addInstance(parts_.get(obj),false);
   		}
   		
 
		for(Object lo : subt.getLinks()){
		   de.cau.cs.kieler.gems.mealy.emf.mealymachine.SubtypeLink link = (de.cau.cs.kieler.gems.mealy.emf.mealymachine.SubtypeLink)lo;
		   esub.createUpdater(parts_.get(link.getBase()),parts_.get(link.getInstance()),link);   
		}
   		return esub;
   	}
   
    public void createTransitionConnection(Container root, de.cau.cs.kieler.gems.mealy.emf.mealymachine.TransitionConnection con){
        if(con.getSource() == null || con.getTarget() ==  null)
           return;
    	ModelObject src = parts_.get(con.getSource());
    	ModelObject trg = parts_.get(con.getTarget());
    	if(src == null || trg == null)
    	   return;
    	   
    	if(connected_.get(src.getID()+"->"+trg.getID()+"::TransitionConnection") != null)
    	   return;
    	   
    	if(!isContainedOrLinked(root, src) || !isContainedOrLinked(root, trg))
    		return;
    		
    	Wire w = new Wire();
    	w.setSource(src,false);
    	w.setTarget(trg,false);
    	w.setSourceTerminal("0");
    	w.setTargetTerminal("0");
    	EMFTransitionProxy proxy = new EMFTransitionProxy(con);
    	w.setConnectionType(TransitionConnectionType.INSTANCE, false);
    	TransitionConnectionType.INSTANCE.installAttributes(w,proxy);
    	src.connectOutput(w,false);
    	trg.connectInput(w,false);
    	wires_.add(w);
    	connected_.put(src.getID()+"->"+trg.getID()+"::TransitionConnection",Boolean.TRUE);
    }
    
    public void createTransitionConnection(Container root, ModelObject src, ModelObject trg){

    	if(src == null || trg == null)
    	   return;
    	   
    	if(connected_.get(src.getID()+"->"+trg.getID()+"::TransitionConnection") != null)
    	   return;
    	   
    	if(!isContainedOrLinked(root, src) || !isContainedOrLinked(root, trg))
    		return;
    		
    	Wire w = new Wire();
    	w.setSource(src,false);
    	w.setTarget(trg,false);
    	w.setSourceTerminal("0");
    	w.setTargetTerminal("0");
    	w.setConnectionType(TransitionConnectionType.INSTANCE, false);
    	src.connectOutput(w,false);
    	trg.connectInput(w,false);
    	wires_.add(w);
    	connected_.put(src.getID()+"->"+trg.getID()+"::TransitionConnection",Boolean.TRUE);
    }
    
    public ModelObject getPart(Container root, Object key){
		return getPart(root,key,true);
	}
	
	public ModelObject getPart(Object key){
		return getPart(null,key,true);
	}
	
	public boolean isContainedOrLinked(Container root, ModelObject curr){
    	return root.firstCommonParent(curr) != null;
    }
	
	public ModelObject getPart(Container root, Object key, boolean load){
		ModelObject part = parts_.get(key);
		if(part == null && key instanceof de.cau.cs.kieler.gems.mealy.emf.mealymachine.ModelObject && key != null){
		    de.cau.cs.kieler.gems.mealy.emf.mealymachine.ModelObject obj = (de.cau.cs.kieler.gems.mealy.emf.mealymachine.ModelObject)key;
		    if(obj.eResource() != null)
		   	   part = parts_.get(obj.eResource().getURI().toString()+"#"+obj.getId());
		}
		if(part == null && load){
			part = load(root,key);
		}
		return part;
	}
	
	public void addDeferredRequest(Runnable request){
		requests_.add(request);
	}
}

