

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;

import java.util.Hashtable;
import org.eclipse.swt.graphics.Color;
import org.eclipse.gmt.gems.model.ConnectionDecoration;
import org.eclipse.draw2d.ColorConstants;
import org.eclipse.gmt.gems.model.ConnectionAppearance;
import org.eclipse.gmt.gems.figures.Hints;
import org.eclipse.gmt.gems.Aspect;
import org.eclipse.gmt.gems.ModelProvider;
import org.eclipse.gmt.gems.model.ModelObject;
import org.eclipse.swt.widgets.Display;

public class GraphicsProviderImpl extends org.eclipse.gmt.gems.model.GraphicsProviderImpl {
   
    public String getModelID() {
        return MealyMachineProvider.MODEL_ID;
    }
   
    protected void createAspects() {
     super.createAspects();
    }
   
    protected void createConnectionAppearances() {
        	ConnectionAppearance Transitionattr = new ConnectionAppearance(
                ConnectionAppearance.NONE,
                ConnectionAppearance.ARROW,
                Hints.getColor("(0,0,0)"),
                0,
                1
              );
        	connectionAppearances_.put(TransitionConnectionType.INSTANCE,Transitionattr);
             
        super.createConnectionAppearances();
    }
    protected void createConnectionDecorations() {
        
        super.createConnectionDecorations();
    }
    
    protected void createDrawingHints() {
    	
    	Hashtable MealyMachine_hints = new Hashtable(7);
    	
		
		MealyMachine_hints.put("background-color", "(255,255,255)");
		
		
		MealyMachine_hints.put("draw-name", "true");
		
		
		MealyMachine_hints.put("draw-type", "true");
		
		
		MealyMachine_hints.put("label-font", "default");
		
		
		MealyMachine_hints.put("label-fontsize", "10");
		
		
		MealyMachine_hints.put("label-fontstyle", "normal");
		
		
		MealyMachine_hints.put("label-foreground", "(0,0,0)");
		
		
		MealyMachine_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(MealyMachine.class, MealyMachine_hints);
		
    	Hashtable State_hints = new Hashtable(7);
    	
		
		State_hints.put("background-color", "(255,255,255)");
		
		
		State_hints.put("draw-name", "true");
		
		
		State_hints.put("draw-type", "true");
		
		
		State_hints.put("label-font", "default");
		
		
		State_hints.put("label-fontsize", "10");
		
		
		State_hints.put("label-fontstyle", "normal");
		
		
		State_hints.put("label-foreground", "(0,0,0)");
		
		
		State_hints.put("label-background", "(255,255,255)");
		
		drawingHints_.put(State.class, State_hints);
		
		super.createDrawingHints();
	}
    
    public ModelProvider getModelProvider() {
        return MealyMachineProvider.getInstance();
    }
}


