

/*
 * Created on Tue Aug 26 17:32:57 CEST 2008
 *
 * Generated by GEMS 
 */
 
package de.cau.cs.kieler.gems.mealy.mealymachine;

import java.util.List;


import org.eclipse.gmt.gems.metamodel.gen.AttributeInfo;
import org.eclipse.gmt.gems.model.AttributeValidator;
import org.eclipse.gmt.gems.ModelProvider;
import org.eclipse.gmt.gems.ModelRepository;
import org.eclipse.gmt.gems.model.Visitor;
import org.eclipse.gmt.gems.model.ConnectionType;
import org.eclipse.gmt.gems.model.Wire;
import org.eclipse.ui.views.properties.IPropertyDescriptor;

import java.util.Vector;
import org.eclipse.gmt.gems.model.ConstraintViolation;

import org.eclipse.gmt.gems.model.Container;
import org.eclipse.gmt.gems.model.LogicElement;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import de.cau.cs.kieler.gems.mealy.emf.mealymachine.*;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;


public class Root extends org.eclipse.gmt.gems.model.Root  implements Adapter{

	private Object model_;
	private Notifier target_;
	
	
	public Root(){
		
	}
	
	public Root(Object mdl){
		model_ = mdl;
	}
	
	public de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root getEMFObject(){
		return getModel();
	}
	
	
	public void setRealRoot(MealyMachine n){
		getModel().setRealRoot(n.getEMFObject());
		children.clear();
		List nchildren = n.getChildren();
		for(Object o : nchildren){
			children.add((org.eclipse.gmt.gems.model.ModelObject)o);
		}
		if(realRoot_ != null){
			realRoot_.removePropertyChangeListener(this);
		}
		realRoot_ = n;
		if(realRoot_ != null){
			realRoot_.addPropertyChangeListener(this);
		}
	}
	
	public MealyMachine getRealRoot(){
		return (MealyMachine)realRoot_;
	}
	
	
	

	
	
    public String getModelID() {
        return MealyMachineProvider.MODEL_ID;
    }
    
    public de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root getModel(){
    	if(model_ == null){
    		model_ = de.cau.cs.kieler.gems.mealy.emf.mealymachine.impl.MealyMachineFactoryImpl.eINSTANCE.createRoot();
    		((de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root)model_).eAdapters().add(this);	
    	}
    	return (de.cau.cs.kieler.gems.mealy.emf.mealymachine.Root)model_;
    }
    	
    	public Notifier getTarget() {
    		return target_;
    	}
    	
    	public void setTarget(Notifier newTarget) {
    		target_ = newTarget;
    	}
    	
    	public boolean isAdapterForType(Object type) {
    		return getModel() == type;
    	}
    
     
    public ModelProvider getModelProvider() {
        ModelProvider provider = super.getModelProvider();
        if(provider == null){
        	provider = new MealyMachineProvider();
        	ModelRepository.getInstance().registerModelProvider(provider);
        }
        return provider;
    }
    
    protected void buildContainmentNames() {
       
    }
    
    
    public void addChild(LogicElement child, int index) {
        addChild(child,index,true);
    }
    
     public void addChild(LogicElement child, int index, boolean modifymodel) {
        if(modifymodel){
    	if(child instanceof MealyMachine){
    		getModel().getMealyMachine().add(((MealyMachine)child).getEMFObject());
    	}
    	
    	if(child instanceof State){
    		getModel().getState().add(((State)child).getEMFObject());
    	}
    	
    	
    	}
    	super.addChild(child,index,modifymodel);
    }
    
    public void removeChild(LogicElement child){
     	removeChild(child,true);
    }
    
    public void removeChild(LogicElement child, boolean modifymodel){
    	if(modifymodel){
     	
    	if(child instanceof MealyMachine){
    		getModel().getMealyMachine().remove(((MealyMachine)child).getEMFObject());
    	}
    	
    	if(child instanceof State){
    		getModel().getState().remove(((State)child).getEMFObject());
    	}
    	
    	
    	}
    	super.removeChild(child,modifymodel);
    }
    

	public void addConnection(Wire w) {
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
			if(con != null){
				getModel().getTransitionConnection().add(con);
			}
		}
		
	
	}
	}
	public void notifyChanged(Notification notification) {}
	
	public void removeConnection(Wire w) {
	ConnectionType type = w.getConnectionType();
	if(type != null){
	
		if(type.getName().equals(TransitionConnectionType.NAME)){
			TransitionConnection con = (TransitionConnection)w.getAttribute(TransitionConnectionType.NAME);
			if(con != null){
				getModel().getTransitionConnection().remove(con);
			}
		}
	
	}
	}
	
	
}

